
[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug=1
[dependencies]

http={path="../http"}

[[bin]]
name="test_http5"
path="replay_files/replay_http5.rs"


[[bin]]
name="test_http8"
path="replay_files/replay_http8.rs"


[[bin]]
name="test_http14"
path="replay_files/replay_http14.rs"


[[bin]]
name="test_http12"
path="replay_files/replay_http12.rs"


[[bin]]
name="test_http2"
path="replay_files/replay_http2.rs"


[[bin]]
name="test_http11"
path="replay_files/replay_http11.rs"


[[bin]]
name="test_http13"
path="replay_files/replay_http13.rs"


[[bin]]
name="test_http3"
path="replay_files/replay_http3.rs"


[[bin]]
name="test_http6"
path="replay_files/replay_http6.rs"


[[bin]]
name="test_http7"
path="replay_files/replay_http7.rs"


[[bin]]
name="test_http10"
path="replay_files/replay_http10.rs"


[[bin]]
name="test_http4"
path="replay_files/replay_http4.rs"


[[bin]]
name="test_http18"
path="replay_files/replay_http18.rs"


[[bin]]
name="test_http9"
path="replay_files/replay_http9.rs"


[[bin]]
name="test_http15"
path="replay_files/replay_http15.rs"


[[bin]]
name="test_http0"
path="replay_files/replay_http0.rs"


[[bin]]
name="test_http1"
path="replay_files/replay_http1.rs"


[[bin]]
name="test_http16"
path="replay_files/replay_http16.rs"


[[bin]]
name="test_http17"
path="replay_files/replay_http17.rs"

