[[bin]]
name = "test_clap31"
path = "replay_files/replay_clap31.rs"

[[bin]]
name = "test_clap16"
path = "replay_files/replay_clap16.rs"

[[bin]]
name = "test_clap9"
path = "replay_files/replay_clap9.rs"

[[bin]]
name = "test_clap46"
path = "replay_files/replay_clap46.rs"

[[bin]]
name = "test_clap17"
path = "replay_files/replay_clap17.rs"

[[bin]]
name = "test_clap27"
path = "replay_files/replay_clap27.rs"

[[bin]]
name = "test_clap10"
path = "replay_files/replay_clap10.rs"

[[bin]]
name = "test_clap35"
path = "replay_files/replay_clap35.rs"

[[bin]]
name = "test_clap8"
path = "replay_files/replay_clap8.rs"

[[bin]]
name = "test_clap32"
path = "replay_files/replay_clap32.rs"

[[bin]]
name = "test_clap52"
path = "replay_files/replay_clap52.rs"

[[bin]]
name = "test_clap24"
path = "replay_files/replay_clap24.rs"

[[bin]]
name = "test_clap21"
path = "replay_files/replay_clap21.rs"

[[bin]]
name = "test_clap26"
path = "replay_files/replay_clap26.rs"

[[bin]]
name = "test_clap5"
path = "replay_files/replay_clap5.rs"

[[bin]]
name = "test_clap28"
path = "replay_files/replay_clap28.rs"

[[bin]]
name = "test_clap2"
path = "replay_files/replay_clap2.rs"

[[bin]]
name = "test_clap38"
path = "replay_files/replay_clap38.rs"

[[bin]]
name = "test_clap37"
path = "replay_files/replay_clap37.rs"

[[bin]]
name = "test_clap51"
path = "replay_files/replay_clap51.rs"

[[bin]]
name = "test_clap50"
path = "replay_files/replay_clap50.rs"

[[bin]]
name = "test_clap57"
path = "replay_files/replay_clap57.rs"

[[bin]]
name = "test_clap49"
path = "replay_files/replay_clap49.rs"

[[bin]]
name = "test_clap36"
path = "replay_files/replay_clap36.rs"

[[bin]]
name = "test_clap3"
path = "replay_files/replay_clap3.rs"

[[bin]]
name = "test_clap30"
path = "replay_files/replay_clap30.rs"

[[bin]]
name = "test_clap20"
path = "replay_files/replay_clap20.rs"

[[bin]]
name = "test_clap43"
path = "replay_files/replay_clap43.rs"

[[bin]]
name = "test_clap29"
path = "replay_files/replay_clap29.rs"

[[bin]]
name = "test_clap14"
path = "replay_files/replay_clap14.rs"

[[bin]]
name = "test_clap7"
path = "replay_files/replay_clap7.rs"

[[bin]]
name = "test_clap4"
path = "replay_files/replay_clap4.rs"

[[bin]]
name = "test_clap12"
path = "replay_files/replay_clap12.rs"

[[bin]]
name = "test_clap54"
path = "replay_files/replay_clap54.rs"

[[bin]]
name = "test_clap55"
path = "replay_files/replay_clap55.rs"

[[bin]]
name = "test_clap45"
path = "replay_files/replay_clap45.rs"

[[bin]]
name = "test_clap6"
path = "replay_files/replay_clap6.rs"

[[bin]]
name = "test_clap1"
path = "replay_files/replay_clap1.rs"

[[bin]]
name = "test_clap25"
path = "replay_files/replay_clap25.rs"

[[bin]]
name = "test_clap53"
path = "replay_files/replay_clap53.rs"

[[bin]]
name = "test_clap56"
path = "replay_files/replay_clap56.rs"

[[bin]]
name = "test_clap39"
path = "replay_files/replay_clap39.rs"

[[bin]]
name = "test_clap44"
path = "replay_files/replay_clap44.rs"

[[bin]]
name = "test_clap40"
path = "replay_files/replay_clap40.rs"

[[bin]]
name = "test_clap19"
path = "replay_files/replay_clap19.rs"

[[bin]]
name = "test_clap18"
path = "replay_files/replay_clap18.rs"

[[bin]]
name = "test_clap58"
path = "replay_files/replay_clap58.rs"

[[bin]]
name = "test_clap11"
path = "replay_files/replay_clap11.rs"

[[bin]]
name = "test_clap34"
path = "replay_files/replay_clap34.rs"

[[bin]]
name = "test_clap33"
path = "replay_files/replay_clap33.rs"

[[bin]]
name = "test_clap48"
path = "replay_files/replay_clap48.rs"

[[bin]]
name = "test_clap42"
path = "replay_files/replay_clap42.rs"

[[bin]]
name = "test_clap15"
path = "replay_files/replay_clap15.rs"

[[bin]]
name = "test_clap41"
path = "replay_files/replay_clap41.rs"

[[bin]]
name = "test_clap0"
path = "replay_files/replay_clap0.rs"

[[bin]]
name = "test_clap22"
path = "replay_files/replay_clap22.rs"

[[bin]]
name = "test_clap47"
path = "replay_files/replay_clap47.rs"

[[bin]]
name = "test_clap23"
path = "replay_files/replay_clap23.rs"

[[bin]]
name = "test_clap13"
path = "replay_files/replay_clap13.rs"

[package]
name = "hello"
version = "0.1.0"
authors = [ "xiang",]
edition = "2018"

[dependencies.clap]
path = "../clap"

[profile.release]
debug = 1
