
[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug=1
[dependencies]

afl="=0.11.1"
serde_json={path="../serde-json"}

[[bin]]
name="test_serde_json15"
path="test_files/test_serde_json15.rs"


[[bin]]
name="test_serde_json9"
path="test_files/test_serde_json9.rs"


[[bin]]
name="test_serde_json14"
path="test_files/test_serde_json14.rs"


[[bin]]
name="test_serde_json2"
path="test_files/test_serde_json2.rs"


[[bin]]
name="test_serde_json12"
path="test_files/test_serde_json12.rs"


[[bin]]
name="test_serde_json21"
path="test_files/test_serde_json21.rs"


[[bin]]
name="test_serde_json17"
path="test_files/test_serde_json17.rs"


[[bin]]
name="test_serde_json11"
path="test_files/test_serde_json11.rs"


[[bin]]
name="test_serde_json16"
path="test_files/test_serde_json16.rs"


[[bin]]
name="test_serde_json23"
path="test_files/test_serde_json23.rs"


[[bin]]
name="test_serde_json7"
path="test_files/test_serde_json7.rs"


[[bin]]
name="test_serde_json22"
path="test_files/test_serde_json22.rs"


[[bin]]
name="test_serde_json1"
path="test_files/test_serde_json1.rs"


[[bin]]
name="test_serde_json3"
path="test_files/test_serde_json3.rs"


[[bin]]
name="test_serde_json13"
path="test_files/test_serde_json13.rs"


[[bin]]
name="test_serde_json20"
path="test_files/test_serde_json20.rs"


[[bin]]
name="test_serde_json4"
path="test_files/test_serde_json4.rs"


[[bin]]
name="test_serde_json19"
path="test_files/test_serde_json19.rs"


[[bin]]
name="test_serde_json0"
path="test_files/test_serde_json0.rs"


[[bin]]
name="test_serde_json5"
path="test_files/test_serde_json5.rs"


[[bin]]
name="test_serde_json24"
path="test_files/test_serde_json24.rs"


[[bin]]
name="test_serde_json10"
path="test_files/test_serde_json10.rs"


[[bin]]
name="test_serde_json18"
path="test_files/test_serde_json18.rs"


[[bin]]
name="test_serde_json6"
path="test_files/test_serde_json6.rs"


[[bin]]
name="test_serde_json8"
path="test_files/test_serde_json8.rs"

