[package]
name = "serde_toml"
version = "0.0.1"
keywords = [ "encoding", "toml",]
categories = [ "encoding", "parser-implementations", "parsing", "config",]
description = "See instead `toml`"

[dependencies]
bolero = "0.8.0"
arbitrary = "1.3.2"

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.include]
workspace = true
