[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl="=0.11.1"
proc-macro2={path="../proc-macro2"}


[profile.release]
debug=1

[[bin]]
name="test_proc_macro213"
path="test_files/test_proc_macro213.rs"


[[bin]]
name="test_proc_macro223"
path="test_files/test_proc_macro223.rs"


[[bin]]
name="test_proc_macro226"
path="test_files/test_proc_macro226.rs"


[[bin]]
name="test_proc_macro212"
path="test_files/test_proc_macro212.rs"


[[bin]]
name="test_proc_macro221"
path="test_files/test_proc_macro221.rs"


[[bin]]
name="test_proc_macro225"
path="test_files/test_proc_macro225.rs"


[[bin]]
name="test_proc_macro20"
path="test_files/test_proc_macro20.rs"


[[bin]]
name="test_proc_macro22"
path="test_files/test_proc_macro22.rs"


[[bin]]
name="test_proc_macro222"
path="test_files/test_proc_macro222.rs"


[[bin]]
name="test_proc_macro215"
path="test_files/test_proc_macro215.rs"


[[bin]]
name="test_proc_macro228"
path="test_files/test_proc_macro228.rs"


[[bin]]
name="test_proc_macro216"
path="test_files/test_proc_macro216.rs"


[[bin]]
name="test_proc_macro210"
path="test_files/test_proc_macro210.rs"


[[bin]]
name="test_proc_macro229"
path="test_files/test_proc_macro229.rs"


[[bin]]
name="test_proc_macro220"
path="test_files/test_proc_macro220.rs"


[[bin]]
name="test_proc_macro21"
path="test_files/test_proc_macro21.rs"


[[bin]]
name="test_proc_macro26"
path="test_files/test_proc_macro26.rs"


[[bin]]
name="test_proc_macro218"
path="test_files/test_proc_macro218.rs"


[[bin]]
name="test_proc_macro29"
path="test_files/test_proc_macro29.rs"


[[bin]]
name="test_proc_macro27"
path="test_files/test_proc_macro27.rs"


[[bin]]
name="test_proc_macro214"
path="test_files/test_proc_macro214.rs"


[[bin]]
name="test_proc_macro227"
path="test_files/test_proc_macro227.rs"


[[bin]]
name="test_proc_macro25"
path="test_files/test_proc_macro25.rs"


[[bin]]
name="test_proc_macro217"
path="test_files/test_proc_macro217.rs"


[[bin]]
name="test_proc_macro219"
path="test_files/test_proc_macro219.rs"


[[bin]]
name="test_proc_macro231"
path="test_files/test_proc_macro231.rs"


[[bin]]
name="test_proc_macro28"
path="test_files/test_proc_macro28.rs"


[[bin]]
name="test_proc_macro211"
path="test_files/test_proc_macro211.rs"


[[bin]]
name="test_proc_macro24"
path="test_files/test_proc_macro24.rs"


[[bin]]
name="test_proc_macro230"
path="test_files/test_proc_macro230.rs"


[[bin]]
name="test_proc_macro224"
path="test_files/test_proc_macro224.rs"


[[bin]]
name="test_proc_macro23"
path="test_files/test_proc_macro23.rs"

