[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl="=0.11.1"
regex={path="../regex"}
[profile.release]
debug=1

[[bin]]
name="test_regex32"
path="test_files/test_regex32.rs"


[[bin]]
name="test_regex66"
path="test_files/test_regex66.rs"


[[bin]]
name="test_regex27"
path="test_files/test_regex27.rs"


[[bin]]
name="test_regex57"
path="test_files/test_regex57.rs"


[[bin]]
name="test_regex70"
path="test_files/test_regex70.rs"


[[bin]]
name="test_regex52"
path="test_files/test_regex52.rs"


[[bin]]
name="test_regex38"
path="test_files/test_regex38.rs"


[[bin]]
name="test_regex39"
path="test_files/test_regex39.rs"


[[bin]]
name="test_regex54"
path="test_files/test_regex54.rs"


[[bin]]
name="test_regex6"
path="test_files/test_regex6.rs"


[[bin]]
name="test_regex4"
path="test_files/test_regex4.rs"


[[bin]]
name="test_regex68"
path="test_files/test_regex68.rs"


[[bin]]
name="test_regex16"
path="test_files/test_regex16.rs"


[[bin]]
name="test_regex3"
path="test_files/test_regex3.rs"


[[bin]]
name="test_regex23"
path="test_files/test_regex23.rs"


[[bin]]
name="test_regex26"
path="test_files/test_regex26.rs"


[[bin]]
name="test_regex37"
path="test_files/test_regex37.rs"


[[bin]]
name="test_regex17"
path="test_files/test_regex17.rs"


[[bin]]
name="test_regex30"
path="test_files/test_regex30.rs"


[[bin]]
name="test_regex7"
path="test_files/test_regex7.rs"


[[bin]]
name="test_regex9"
path="test_files/test_regex9.rs"


[[bin]]
name="test_regex28"
path="test_files/test_regex28.rs"


[[bin]]
name="test_regex63"
path="test_files/test_regex63.rs"


[[bin]]
name="test_regex61"
path="test_files/test_regex61.rs"


[[bin]]
name="test_regex58"
path="test_files/test_regex58.rs"


[[bin]]
name="test_regex50"
path="test_files/test_regex50.rs"


[[bin]]
name="test_regex10"
path="test_files/test_regex10.rs"


[[bin]]
name="test_regex24"
path="test_files/test_regex24.rs"


[[bin]]
name="test_regex33"
path="test_files/test_regex33.rs"


[[bin]]
name="test_regex11"
path="test_files/test_regex11.rs"


[[bin]]
name="test_regex19"
path="test_files/test_regex19.rs"


[[bin]]
name="test_regex43"
path="test_files/test_regex43.rs"


[[bin]]
name="test_regex20"
path="test_files/test_regex20.rs"


[[bin]]
name="test_regex14"
path="test_files/test_regex14.rs"


[[bin]]
name="test_regex49"
path="test_files/test_regex49.rs"


[[bin]]
name="test_regex55"
path="test_files/test_regex55.rs"


[[bin]]
name="test_regex42"
path="test_files/test_regex42.rs"


[[bin]]
name="test_regex45"
path="test_files/test_regex45.rs"


[[bin]]
name="test_regex71"
path="test_files/test_regex71.rs"


[[bin]]
name="test_regex22"
path="test_files/test_regex22.rs"


[[bin]]
name="test_regex59"
path="test_files/test_regex59.rs"


[[bin]]
name="test_regex0"
path="test_files/test_regex0.rs"


[[bin]]
name="test_regex1"
path="test_files/test_regex1.rs"


[[bin]]
name="test_regex31"
path="test_files/test_regex31.rs"


[[bin]]
name="test_regex12"
path="test_files/test_regex12.rs"


[[bin]]
name="test_regex60"
path="test_files/test_regex60.rs"


[[bin]]
name="test_regex48"
path="test_files/test_regex48.rs"


[[bin]]
name="test_regex18"
path="test_files/test_regex18.rs"


[[bin]]
name="test_regex5"
path="test_files/test_regex5.rs"


[[bin]]
name="test_regex62"
path="test_files/test_regex62.rs"


[[bin]]
name="test_regex72"
path="test_files/test_regex72.rs"


[[bin]]
name="test_regex2"
path="test_files/test_regex2.rs"


[[bin]]
name="test_regex8"
path="test_files/test_regex8.rs"


[[bin]]
name="test_regex25"
path="test_files/test_regex25.rs"


[[bin]]
name="test_regex67"
path="test_files/test_regex67.rs"


[[bin]]
name="test_regex21"
path="test_files/test_regex21.rs"


[[bin]]
name="test_regex51"
path="test_files/test_regex51.rs"


[[bin]]
name="test_regex47"
path="test_files/test_regex47.rs"


[[bin]]
name="test_regex44"
path="test_files/test_regex44.rs"


[[bin]]
name="test_regex34"
path="test_files/test_regex34.rs"


[[bin]]
name="test_regex13"
path="test_files/test_regex13.rs"


[[bin]]
name="test_regex69"
path="test_files/test_regex69.rs"


[[bin]]
name="test_regex35"
path="test_files/test_regex35.rs"


[[bin]]
name="test_regex64"
path="test_files/test_regex64.rs"


[[bin]]
name="test_regex36"
path="test_files/test_regex36.rs"


[[bin]]
name="test_regex15"
path="test_files/test_regex15.rs"


[[bin]]
name="test_regex29"
path="test_files/test_regex29.rs"


[[bin]]
name="test_regex41"
path="test_files/test_regex41.rs"


[[bin]]
name="test_regex65"
path="test_files/test_regex65.rs"


[[bin]]
name="test_regex73"
path="test_files/test_regex73.rs"


[[bin]]
name="test_regex40"
path="test_files/test_regex40.rs"


[[bin]]
name="test_regex53"
path="test_files/test_regex53.rs"


[[bin]]
name="test_regex56"
path="test_files/test_regex56.rs"


[[bin]]
name="test_regex46"
path="test_files/test_regex46.rs"


