[[test]]
name = "decoder_compliance"
harness = false

[[test]]
name = "encoder_compliance"
harness = false

[[example]]
name = "decode"
required-features = [ "parse", "display",]

[[example]]
name = "enum_external"
required-features = [ "parse", "display",]

[[example]]
name = "toml2json"
required-features = [ "parse", "display",]

[package]
name = "toml"
version = "0.7.5"
keywords = [ "encoding", "toml",]
categories = [ "encoding", "parser-implementations", "parsing", "config",]
description = "A native Rust encoder and decoder of TOML-formatted files and streams. Provides\nimplementations of the standard Serialize/Deserialize traits for TOML data to\nfacilitate deserializing and serializing Rust structures.\n"
authors = [ "Alex Crichton <alex@alexcrichton.com>",]

[features]
default = [ "parse", "display",]
parse = [ "dep:toml_edit",]
display = [ "dep:toml_edit",]
preserve_order = [ "indexmap",]

[dependencies]
serde = "1.0.145"
bolero = "0.8.0"
arbitrary = "1.3.2"

[dev-dependencies]
serde_json = "1.0.96"
toml-test-harness = "0.4.3"
snapbox = "0.4.11"

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.include]
workspace = true

[dependencies.indexmap]
version = "2.0.0"
optional = true

[dependencies.toml_edit]
version = "0.19.11"
path = "../toml_edit"
features = [ "serde",]
optional = true

[dependencies.toml_datetime]
version = "0.6.3"
path = "../toml_datetime"
features = [ "serde",]

[dependencies.serde_spanned]
version = "0.6.3"
path = "../serde_spanned"
features = [ "serde",]

[dev-dependencies.serde]
version = "1.0.160"
features = [ "derive",]

[package.metadata.release]
[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "Unreleased"
replace = "{{version}}"
min = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...{{tag_name}}"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "ReleaseDate"
replace = "{{date}}"
min = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-header -->"
replace = "<!-- next-header -->\n## [Unreleased] - ReleaseDate\n"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-url -->"
replace = "<!-- next-url -->\n[Unreleased]: https://github.com/toml-rs/toml/compare/{{tag_name}}...HEAD"
exactly = 1

[package.metadata.docs.rs]
rustdoc-args = [ "--cfg", "docsrs",]
