[[bin]]
name = "test_flate287"
path = "replay_files/replay_flate287.rs"

[[bin]]
name = "test_flate246"
path = "replay_files/replay_flate246.rs"

[[bin]]
name = "test_flate273"
path = "replay_files/replay_flate273.rs"

[[bin]]
name = "test_flate227"
path = "replay_files/replay_flate227.rs"

[[bin]]
name = "test_flate22"
path = "replay_files/replay_flate22.rs"

[[bin]]
name = "test_flate290"
path = "replay_files/replay_flate290.rs"

[[bin]]
name = "test_flate292"
path = "replay_files/replay_flate292.rs"

[[bin]]
name = "test_flate223"
path = "replay_files/replay_flate223.rs"

[[bin]]
name = "test_flate245"
path = "replay_files/replay_flate245.rs"

[[bin]]
name = "test_flate262"
path = "replay_files/replay_flate262.rs"

[[bin]]
name = "test_flate27"
path = "replay_files/replay_flate27.rs"

[[bin]]
name = "test_flate251"
path = "replay_files/replay_flate251.rs"

[[bin]]
name = "test_flate219"
path = "replay_files/replay_flate219.rs"

[[bin]]
name = "test_flate233"
path = "replay_files/replay_flate233.rs"

[[bin]]
name = "test_flate23"
path = "replay_files/replay_flate23.rs"

[[bin]]
name = "test_flate222"
path = "replay_files/replay_flate222.rs"

[[bin]]
name = "test_flate247"
path = "replay_files/replay_flate247.rs"

[[bin]]
name = "test_flate237"
path = "replay_files/replay_flate237.rs"

[[bin]]
name = "test_flate278"
path = "replay_files/replay_flate278.rs"

[[bin]]
name = "test_flate220"
path = "replay_files/replay_flate220.rs"

[[bin]]
name = "test_flate275"
path = "replay_files/replay_flate275.rs"

[[bin]]
name = "test_flate267"
path = "replay_files/replay_flate267.rs"

[[bin]]
name = "test_flate214"
path = "replay_files/replay_flate214.rs"

[[bin]]
name = "test_flate250"
path = "replay_files/replay_flate250.rs"

[[bin]]
name = "test_flate26"
path = "replay_files/replay_flate26.rs"

[[bin]]
name = "test_flate259"
path = "replay_files/replay_flate259.rs"

[[bin]]
name = "test_flate229"
path = "replay_files/replay_flate229.rs"

[[bin]]
name = "test_flate281"
path = "replay_files/replay_flate281.rs"

[[bin]]
name = "test_flate244"
path = "replay_files/replay_flate244.rs"

[[bin]]
name = "test_flate242"
path = "replay_files/replay_flate242.rs"

[[bin]]
name = "test_flate289"
path = "replay_files/replay_flate289.rs"

[[bin]]
name = "test_flate215"
path = "replay_files/replay_flate215.rs"

[[bin]]
name = "test_flate235"
path = "replay_files/replay_flate235.rs"

[[bin]]
name = "test_flate293"
path = "replay_files/replay_flate293.rs"

[[bin]]
name = "test_flate230"
path = "replay_files/replay_flate230.rs"

[[bin]]
name = "test_flate213"
path = "replay_files/replay_flate213.rs"

[[bin]]
name = "test_flate285"
path = "replay_files/replay_flate285.rs"

[[bin]]
name = "test_flate28"
path = "replay_files/replay_flate28.rs"

[[bin]]
name = "test_flate265"
path = "replay_files/replay_flate265.rs"

[[bin]]
name = "test_flate217"
path = "replay_files/replay_flate217.rs"

[[bin]]
name = "test_flate238"
path = "replay_files/replay_flate238.rs"

[[bin]]
name = "test_flate266"
path = "replay_files/replay_flate266.rs"

[[bin]]
name = "test_flate269"
path = "replay_files/replay_flate269.rs"

[[bin]]
name = "test_flate243"
path = "replay_files/replay_flate243.rs"

[[bin]]
name = "test_flate25"
path = "replay_files/replay_flate25.rs"

[[bin]]
name = "test_flate255"
path = "replay_files/replay_flate255.rs"

[[bin]]
name = "test_flate261"
path = "replay_files/replay_flate261.rs"

[[bin]]
name = "test_flate221"
path = "replay_files/replay_flate221.rs"

[[bin]]
name = "test_flate218"
path = "replay_files/replay_flate218.rs"

[[bin]]
name = "test_flate270"
path = "replay_files/replay_flate270.rs"

[[bin]]
name = "test_flate20"
path = "replay_files/replay_flate20.rs"

[[bin]]
name = "test_flate271"
path = "replay_files/replay_flate271.rs"

[[bin]]
name = "test_flate264"
path = "replay_files/replay_flate264.rs"

[[bin]]
name = "test_flate260"
path = "replay_files/replay_flate260.rs"

[[bin]]
name = "test_flate284"
path = "replay_files/replay_flate284.rs"

[[bin]]
name = "test_flate274"
path = "replay_files/replay_flate274.rs"

[[bin]]
name = "test_flate252"
path = "replay_files/replay_flate252.rs"

[[bin]]
name = "test_flate29"
path = "replay_files/replay_flate29.rs"

[[bin]]
name = "test_flate24"
path = "replay_files/replay_flate24.rs"

[[bin]]
name = "test_flate231"
path = "replay_files/replay_flate231.rs"

[[bin]]
name = "test_flate279"
path = "replay_files/replay_flate279.rs"

[[bin]]
name = "test_flate253"
path = "replay_files/replay_flate253.rs"

[[bin]]
name = "test_flate268"
path = "replay_files/replay_flate268.rs"

[[bin]]
name = "test_flate256"
path = "replay_files/replay_flate256.rs"

[[bin]]
name = "test_flate280"
path = "replay_files/replay_flate280.rs"

[[bin]]
name = "test_flate236"
path = "replay_files/replay_flate236.rs"

[[bin]]
name = "test_flate21"
path = "replay_files/replay_flate21.rs"

[[bin]]
name = "test_flate216"
path = "replay_files/replay_flate216.rs"

[[bin]]
name = "test_flate276"
path = "replay_files/replay_flate276.rs"

[[bin]]
name = "test_flate283"
path = "replay_files/replay_flate283.rs"

[[bin]]
name = "test_flate248"
path = "replay_files/replay_flate248.rs"

[[bin]]
name = "test_flate294"
path = "replay_files/replay_flate294.rs"

[[bin]]
name = "test_flate240"
path = "replay_files/replay_flate240.rs"

[[bin]]
name = "test_flate263"
path = "replay_files/replay_flate263.rs"

[[bin]]
name = "test_flate212"
path = "replay_files/replay_flate212.rs"

[[bin]]
name = "test_flate249"
path = "replay_files/replay_flate249.rs"

[[bin]]
name = "test_flate291"
path = "replay_files/replay_flate291.rs"

[[bin]]
name = "test_flate226"
path = "replay_files/replay_flate226.rs"

[[bin]]
name = "test_flate225"
path = "replay_files/replay_flate225.rs"

[[bin]]
name = "test_flate224"
path = "replay_files/replay_flate224.rs"

[[bin]]
name = "test_flate288"
path = "replay_files/replay_flate288.rs"

[[bin]]
name = "test_flate234"
path = "replay_files/replay_flate234.rs"

[[bin]]
name = "test_flate257"
path = "replay_files/replay_flate257.rs"

[[bin]]
name = "test_flate211"
path = "replay_files/replay_flate211.rs"

[[bin]]
name = "test_flate254"
path = "replay_files/replay_flate254.rs"

[[bin]]
name = "test_flate210"
path = "replay_files/replay_flate210.rs"

[[bin]]
name = "test_flate295"
path = "replay_files/replay_flate295.rs"

[[bin]]
name = "test_flate241"
path = "replay_files/replay_flate241.rs"

[[bin]]
name = "test_flate232"
path = "replay_files/replay_flate232.rs"

[[bin]]
name = "test_flate272"
path = "replay_files/replay_flate272.rs"

[[bin]]
name = "test_flate228"
path = "replay_files/replay_flate228.rs"

[[bin]]
name = "test_flate286"
path = "replay_files/replay_flate286.rs"

[[bin]]
name = "test_flate239"
path = "replay_files/replay_flate239.rs"

[[bin]]
name = "test_flate258"
path = "replay_files/replay_flate258.rs"

[[bin]]
name = "test_flate282"
path = "replay_files/replay_flate282.rs"

[[bin]]
name = "test_flate277"
path = "replay_files/replay_flate277.rs"

[package]
name = "hello"
version = "0.1.0"
authors = [ "xiang",]
edition = "2018"

[dependencies.flate2]
path = "../flate2-rs"

[profile.release]
debug = 1
