[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl="=0.11.1"
flate2={path="../flate2-rs"}
[profile.release]
debug=1
[[bin]]
name="test_flate214"
path="test_files/test_flate214.rs"


[[bin]]
name="test_flate219"
path="test_files/test_flate219.rs"


[[bin]]
name="test_flate236"
path="test_files/test_flate236.rs"


[[bin]]
name="test_flate221"
path="test_files/test_flate221.rs"


[[bin]]
name="test_flate269"
path="test_files/test_flate269.rs"


[[bin]]
name="test_flate232"
path="test_files/test_flate232.rs"


[[bin]]
name="test_flate295"
path="test_files/test_flate295.rs"


[[bin]]
name="test_flate250"
path="test_files/test_flate250.rs"


[[bin]]
name="test_flate229"
path="test_files/test_flate229.rs"


[[bin]]
name="test_flate251"
path="test_files/test_flate251.rs"


[[bin]]
name="test_flate253"
path="test_files/test_flate253.rs"


[[bin]]
name="test_flate260"
path="test_files/test_flate260.rs"


[[bin]]
name="test_flate255"
path="test_files/test_flate255.rs"


[[bin]]
name="test_flate263"
path="test_files/test_flate263.rs"


[[bin]]
name="test_flate222"
path="test_files/test_flate222.rs"


[[bin]]
name="test_flate270"
path="test_files/test_flate270.rs"


[[bin]]
name="test_flate238"
path="test_files/test_flate238.rs"


[[bin]]
name="test_flate228"
path="test_files/test_flate228.rs"


[[bin]]
name="test_flate239"
path="test_files/test_flate239.rs"


[[bin]]
name="test_flate243"
path="test_files/test_flate243.rs"


[[bin]]
name="test_flate20"
path="test_files/test_flate20.rs"


[[bin]]
name="test_flate276"
path="test_files/test_flate276.rs"


[[bin]]
name="test_flate279"
path="test_files/test_flate279.rs"


[[bin]]
name="test_flate215"
path="test_files/test_flate215.rs"


[[bin]]
name="test_flate224"
path="test_files/test_flate224.rs"


[[bin]]
name="test_flate26"
path="test_files/test_flate26.rs"


[[bin]]
name="test_flate28"
path="test_files/test_flate28.rs"


[[bin]]
name="test_flate266"
path="test_files/test_flate266.rs"


[[bin]]
name="test_flate281"
path="test_files/test_flate281.rs"


[[bin]]
name="test_flate237"
path="test_files/test_flate237.rs"


[[bin]]
name="test_flate284"
path="test_files/test_flate284.rs"


[[bin]]
name="test_flate289"
path="test_files/test_flate289.rs"


[[bin]]
name="test_flate211"
path="test_files/test_flate211.rs"


[[bin]]
name="test_flate246"
path="test_files/test_flate246.rs"


[[bin]]
name="test_flate220"
path="test_files/test_flate220.rs"


[[bin]]
name="test_flate210"
path="test_files/test_flate210.rs"


[[bin]]
name="test_flate234"
path="test_files/test_flate234.rs"


[[bin]]
name="test_flate244"
path="test_files/test_flate244.rs"


[[bin]]
name="test_flate24"
path="test_files/test_flate24.rs"


[[bin]]
name="test_flate272"
path="test_files/test_flate272.rs"


[[bin]]
name="test_flate248"
path="test_files/test_flate248.rs"


[[bin]]
name="test_flate230"
path="test_files/test_flate230.rs"


[[bin]]
name="test_flate223"
path="test_files/test_flate223.rs"


[[bin]]
name="test_flate277"
path="test_files/test_flate277.rs"


[[bin]]
name="test_flate225"
path="test_files/test_flate225.rs"


[[bin]]
name="test_flate267"
path="test_files/test_flate267.rs"


[[bin]]
name="test_flate27"
path="test_files/test_flate27.rs"


[[bin]]
name="test_flate258"
path="test_files/test_flate258.rs"


[[bin]]
name="test_flate242"
path="test_files/test_flate242.rs"


[[bin]]
name="test_flate21"
path="test_files/test_flate21.rs"


[[bin]]
name="test_flate247"
path="test_files/test_flate247.rs"


[[bin]]
name="test_flate280"
path="test_files/test_flate280.rs"


[[bin]]
name="test_flate249"
path="test_files/test_flate249.rs"


[[bin]]
name="test_flate274"
path="test_files/test_flate274.rs"


[[bin]]
name="test_flate213"
path="test_files/test_flate213.rs"


[[bin]]
name="test_flate268"
path="test_files/test_flate268.rs"


[[bin]]
name="test_flate259"
path="test_files/test_flate259.rs"


[[bin]]
name="test_flate252"
path="test_files/test_flate252.rs"


[[bin]]
name="test_flate233"
path="test_files/test_flate233.rs"


[[bin]]
name="test_flate226"
path="test_files/test_flate226.rs"


[[bin]]
name="test_flate282"
path="test_files/test_flate282.rs"


[[bin]]
name="test_flate254"
path="test_files/test_flate254.rs"


[[bin]]
name="test_flate261"
path="test_files/test_flate261.rs"


[[bin]]
name="test_flate241"
path="test_files/test_flate241.rs"


[[bin]]
name="test_flate275"
path="test_files/test_flate275.rs"


[[bin]]
name="test_flate278"
path="test_files/test_flate278.rs"


[[bin]]
name="test_flate293"
path="test_files/test_flate293.rs"


[[bin]]
name="test_flate283"
path="test_files/test_flate283.rs"


[[bin]]
name="test_flate216"
path="test_files/test_flate216.rs"


[[bin]]
name="test_flate271"
path="test_files/test_flate271.rs"


[[bin]]
name="test_flate262"
path="test_files/test_flate262.rs"


[[bin]]
name="test_flate286"
path="test_files/test_flate286.rs"


[[bin]]
name="test_flate256"
path="test_files/test_flate256.rs"


[[bin]]
name="test_flate287"
path="test_files/test_flate287.rs"


[[bin]]
name="test_flate245"
path="test_files/test_flate245.rs"


[[bin]]
name="test_flate265"
path="test_files/test_flate265.rs"


[[bin]]
name="test_flate25"
path="test_files/test_flate25.rs"


[[bin]]
name="test_flate235"
path="test_files/test_flate235.rs"


[[bin]]
name="test_flate257"
path="test_files/test_flate257.rs"


[[bin]]
name="test_flate290"
path="test_files/test_flate290.rs"


[[bin]]
name="test_flate288"
path="test_files/test_flate288.rs"


[[bin]]
name="test_flate264"
path="test_files/test_flate264.rs"


[[bin]]
name="test_flate231"
path="test_files/test_flate231.rs"


[[bin]]
name="test_flate218"
path="test_files/test_flate218.rs"


[[bin]]
name="test_flate23"
path="test_files/test_flate23.rs"


[[bin]]
name="test_flate294"
path="test_files/test_flate294.rs"


[[bin]]
name="test_flate29"
path="test_files/test_flate29.rs"


[[bin]]
name="test_flate22"
path="test_files/test_flate22.rs"


[[bin]]
name="test_flate285"
path="test_files/test_flate285.rs"


[[bin]]
name="test_flate217"
path="test_files/test_flate217.rs"


[[bin]]
name="test_flate227"
path="test_files/test_flate227.rs"


[[bin]]
name="test_flate292"
path="test_files/test_flate292.rs"


[[bin]]
name="test_flate273"
path="test_files/test_flate273.rs"


[[bin]]
name="test_flate291"
path="test_files/test_flate291.rs"


[[bin]]
name="test_flate212"
path="test_files/test_flate212.rs"


[[bin]]
name="test_flate240"
path="test_files/test_flate240.rs"

