name: CI
on:
  pull_request:
  push:
    branches:
    - main
  schedule:
  - cron: '19 19 19 * *'
jobs:
  ci:
    name: CI
    needs: [test, msrv, docs, rustfmt, clippy]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  test:
    name: Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        rust: ["stable"]
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo test --no-run --workspace
    - name: Default features
      run: cargo test --workspace
    - name: toml_edit (all features)
      run: cargo test -p toml_edit --all-features
    - name: toml_edit (no-default features)
      run: cargo test -p toml_edit --no-default-features
    - name: toml (preserve_order)
      run: cargo test -p toml --features preserve_order
    - name: toml (all features)
      run: cargo test -p toml --all-features
    - name: toml (parse-only)
      run: cargo test -p toml --no-default-features --features parse
    - name: toml (display-only)
      run: cargo test -p toml --no-default-features --features display
    - name: toml (no-default features)
      run: cargo test -p toml --no-default-features
  msrv:
    name: "Check MSRV: 1.64.0"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: 1.64.0  # MSRV
    - uses: Swatinem/rust-cache@v2
    - name: Default features
      run: cargo check --workspace --all-targets
    - name: All features
      run: cargo check --workspace --all-targets --all-features
    - name: No-default features
      run: cargo check --workspace --all-targets --no-default-features
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: Check documentation
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --workspace --all-features --no-deps --document-private-items
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        # Not MSRV because its harder to jump between versions and people are
        # more likely to have stable
        toolchain: stable
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: 1.64.0  # MSRV
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --workspace --all-features --all-targets -- -D warnings --allow deprecated
