
[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug=1
[dependencies]

afl="=0.11.1"
regex-syntax={path="../regex-syntax"}

[[bin]]
name="test_regex_syntax12"
path="test_files/test_regex_syntax12.rs"


[[bin]]
name="test_regex_syntax60"
path="test_files/test_regex_syntax60.rs"


[[bin]]
name="test_regex_syntax68"
path="test_files/test_regex_syntax68.rs"


[[bin]]
name="test_regex_syntax26"
path="test_files/test_regex_syntax26.rs"


[[bin]]
name="test_regex_syntax19"
path="test_files/test_regex_syntax19.rs"


[[bin]]
name="test_regex_syntax32"
path="test_files/test_regex_syntax32.rs"


[[bin]]
name="test_regex_syntax54"
path="test_files/test_regex_syntax54.rs"


[[bin]]
name="test_regex_syntax4"
path="test_files/test_regex_syntax4.rs"


[[bin]]
name="test_regex_syntax10"
path="test_files/test_regex_syntax10.rs"


[[bin]]
name="test_regex_syntax29"
path="test_files/test_regex_syntax29.rs"


[[bin]]
name="test_regex_syntax67"
path="test_files/test_regex_syntax67.rs"


[[bin]]
name="test_regex_syntax55"
path="test_files/test_regex_syntax55.rs"


[[bin]]
name="test_regex_syntax24"
path="test_files/test_regex_syntax24.rs"


[[bin]]
name="test_regex_syntax14"
path="test_files/test_regex_syntax14.rs"


[[bin]]
name="test_regex_syntax63"
path="test_files/test_regex_syntax63.rs"


[[bin]]
name="test_regex_syntax37"
path="test_files/test_regex_syntax37.rs"


[[bin]]
name="test_regex_syntax49"
path="test_files/test_regex_syntax49.rs"


[[bin]]
name="test_regex_syntax22"
path="test_files/test_regex_syntax22.rs"


[[bin]]
name="test_regex_syntax6"
path="test_files/test_regex_syntax6.rs"


[[bin]]
name="test_regex_syntax50"
path="test_files/test_regex_syntax50.rs"


[[bin]]
name="test_regex_syntax28"
path="test_files/test_regex_syntax28.rs"


[[bin]]
name="test_regex_syntax5"
path="test_files/test_regex_syntax5.rs"


[[bin]]
name="test_regex_syntax21"
path="test_files/test_regex_syntax21.rs"


[[bin]]
name="test_regex_syntax20"
path="test_files/test_regex_syntax20.rs"


[[bin]]
name="test_regex_syntax42"
path="test_files/test_regex_syntax42.rs"


[[bin]]
name="test_regex_syntax52"
path="test_files/test_regex_syntax52.rs"


[[bin]]
name="test_regex_syntax56"
path="test_files/test_regex_syntax56.rs"


[[bin]]
name="test_regex_syntax2"
path="test_files/test_regex_syntax2.rs"


[[bin]]
name="test_regex_syntax36"
path="test_files/test_regex_syntax36.rs"


[[bin]]
name="test_regex_syntax70"
path="test_files/test_regex_syntax70.rs"


[[bin]]
name="test_regex_syntax71"
path="test_files/test_regex_syntax71.rs"


[[bin]]
name="test_regex_syntax0"
path="test_files/test_regex_syntax0.rs"


[[bin]]
name="test_regex_syntax1"
path="test_files/test_regex_syntax1.rs"


[[bin]]
name="test_regex_syntax15"
path="test_files/test_regex_syntax15.rs"


[[bin]]
name="test_regex_syntax18"
path="test_files/test_regex_syntax18.rs"


[[bin]]
name="test_regex_syntax61"
path="test_files/test_regex_syntax61.rs"


[[bin]]
name="test_regex_syntax7"
path="test_files/test_regex_syntax7.rs"


[[bin]]
name="test_regex_syntax57"
path="test_files/test_regex_syntax57.rs"


[[bin]]
name="test_regex_syntax38"
path="test_files/test_regex_syntax38.rs"


[[bin]]
name="test_regex_syntax13"
path="test_files/test_regex_syntax13.rs"


[[bin]]
name="test_regex_syntax35"
path="test_files/test_regex_syntax35.rs"


[[bin]]
name="test_regex_syntax45"
path="test_files/test_regex_syntax45.rs"


[[bin]]
name="test_regex_syntax44"
path="test_files/test_regex_syntax44.rs"


[[bin]]
name="test_regex_syntax72"
path="test_files/test_regex_syntax72.rs"


[[bin]]
name="test_regex_syntax51"
path="test_files/test_regex_syntax51.rs"


[[bin]]
name="test_regex_syntax58"
path="test_files/test_regex_syntax58.rs"


[[bin]]
name="test_regex_syntax16"
path="test_files/test_regex_syntax16.rs"


[[bin]]
name="test_regex_syntax62"
path="test_files/test_regex_syntax62.rs"


[[bin]]
name="test_regex_syntax30"
path="test_files/test_regex_syntax30.rs"


[[bin]]
name="test_regex_syntax17"
path="test_files/test_regex_syntax17.rs"


[[bin]]
name="test_regex_syntax3"
path="test_files/test_regex_syntax3.rs"


[[bin]]
name="test_regex_syntax46"
path="test_files/test_regex_syntax46.rs"


[[bin]]
name="test_regex_syntax66"
path="test_files/test_regex_syntax66.rs"


[[bin]]
name="test_regex_syntax9"
path="test_files/test_regex_syntax9.rs"


[[bin]]
name="test_regex_syntax69"
path="test_files/test_regex_syntax69.rs"


[[bin]]
name="test_regex_syntax31"
path="test_files/test_regex_syntax31.rs"


[[bin]]
name="test_regex_syntax41"
path="test_files/test_regex_syntax41.rs"


[[bin]]
name="test_regex_syntax39"
path="test_files/test_regex_syntax39.rs"


[[bin]]
name="test_regex_syntax65"
path="test_files/test_regex_syntax65.rs"


[[bin]]
name="test_regex_syntax53"
path="test_files/test_regex_syntax53.rs"


[[bin]]
name="test_regex_syntax23"
path="test_files/test_regex_syntax23.rs"


[[bin]]
name="test_regex_syntax33"
path="test_files/test_regex_syntax33.rs"


[[bin]]
name="test_regex_syntax27"
path="test_files/test_regex_syntax27.rs"


[[bin]]
name="test_regex_syntax8"
path="test_files/test_regex_syntax8.rs"


[[bin]]
name="test_regex_syntax64"
path="test_files/test_regex_syntax64.rs"


[[bin]]
name="test_regex_syntax40"
path="test_files/test_regex_syntax40.rs"


[[bin]]
name="test_regex_syntax43"
path="test_files/test_regex_syntax43.rs"


[[bin]]
name="test_regex_syntax11"
path="test_files/test_regex_syntax11.rs"


[[bin]]
name="test_regex_syntax25"
path="test_files/test_regex_syntax25.rs"


[[bin]]
name="test_regex_syntax48"
path="test_files/test_regex_syntax48.rs"


[[bin]]
name="test_regex_syntax34"
path="test_files/test_regex_syntax34.rs"


[[bin]]
name="test_regex_syntax59"
path="test_files/test_regex_syntax59.rs"


[[bin]]
name="test_regex_syntax47"
path="test_files/test_regex_syntax47.rs"

