[[bin]]
name="test_xi_core_lib21"
path="replay_files/replay_xi_core_lib21.rs"


[[bin]]
name="test_xi_core_lib39"
path="replay_files/replay_xi_core_lib39.rs"


[[bin]]
name="test_xi_core_lib14"
path="replay_files/replay_xi_core_lib14.rs"


[[bin]]
name="test_xi_core_lib0"
path="replay_files/replay_xi_core_lib0.rs"


[[bin]]
name="test_xi_core_lib9"
path="replay_files/replay_xi_core_lib9.rs"


[[bin]]
name="test_xi_core_lib19"
path="replay_files/replay_xi_core_lib19.rs"


[[bin]]
name="test_xi_core_lib18"
path="replay_files/replay_xi_core_lib18.rs"


[[bin]]
name="test_xi_core_lib32"
path="replay_files/replay_xi_core_lib32.rs"


[[bin]]
name="test_xi_core_lib34"
path="replay_files/replay_xi_core_lib34.rs"


[[bin]]
name="test_xi_core_lib30"
path="replay_files/replay_xi_core_lib30.rs"


[[bin]]
name="test_xi_core_lib24"
path="replay_files/replay_xi_core_lib24.rs"


[[bin]]
name="test_xi_core_lib13"
path="replay_files/replay_xi_core_lib13.rs"


[[bin]]
name="test_xi_core_lib2"
path="replay_files/replay_xi_core_lib2.rs"


[[bin]]
name="test_xi_core_lib36"
path="replay_files/replay_xi_core_lib36.rs"


[[bin]]
name="test_xi_core_lib33"
path="replay_files/replay_xi_core_lib33.rs"


[[bin]]
name="test_xi_core_lib15"
path="replay_files/replay_xi_core_lib15.rs"


[[bin]]
name="test_xi_core_lib16"
path="replay_files/replay_xi_core_lib16.rs"


[[bin]]
name="test_xi_core_lib12"
path="replay_files/replay_xi_core_lib12.rs"


[[bin]]
name="test_xi_core_lib38"
path="replay_files/replay_xi_core_lib38.rs"


[[bin]]
name="test_xi_core_lib31"
path="replay_files/replay_xi_core_lib31.rs"


[[bin]]
name="test_xi_core_lib4"
path="replay_files/replay_xi_core_lib4.rs"


[[bin]]
name="test_xi_core_lib35"
path="replay_files/replay_xi_core_lib35.rs"


[[bin]]
name="test_xi_core_lib8"
path="replay_files/replay_xi_core_lib8.rs"


[[bin]]
name="test_xi_core_lib22"
path="replay_files/replay_xi_core_lib22.rs"


[[bin]]
name="test_xi_core_lib10"
path="replay_files/replay_xi_core_lib10.rs"


[[bin]]
name="test_xi_core_lib17"
path="replay_files/replay_xi_core_lib17.rs"


[[bin]]
name="test_xi_core_lib3"
path="replay_files/replay_xi_core_lib3.rs"


[[bin]]
name="test_xi_core_lib11"
path="replay_files/replay_xi_core_lib11.rs"


[[bin]]
name="test_xi_core_lib1"
path="replay_files/replay_xi_core_lib1.rs"


[[bin]]
name="test_xi_core_lib37"
path="replay_files/replay_xi_core_lib37.rs"


[[bin]]
name="test_xi_core_lib25"
path="replay_files/replay_xi_core_lib25.rs"


[[bin]]
name="test_xi_core_lib29"
path="replay_files/replay_xi_core_lib29.rs"


[[bin]]
name="test_xi_core_lib27"
path="replay_files/replay_xi_core_lib27.rs"


[[bin]]
name="test_xi_core_lib23"
path="replay_files/replay_xi_core_lib23.rs"


[[bin]]
name="test_xi_core_lib6"
path="replay_files/replay_xi_core_lib6.rs"


[[bin]]
name="test_xi_core_lib5"
path="replay_files/replay_xi_core_lib5.rs"


[[bin]]
name="test_xi_core_lib26"
path="replay_files/replay_xi_core_lib26.rs"


[[bin]]
name="test_xi_core_lib20"
path="replay_files/replay_xi_core_lib20.rs"


[[bin]]
name="test_xi_core_lib28"
path="replay_files/replay_xi_core_lib28.rs"


[[bin]]
name="test_xi_core_lib7"
path="replay_files/replay_xi_core_lib7.rs"

[package]
name = "hello"
version = "0.1.0"
authors = [ "xiang",]
edition = "2018"

[dependencies.xi-core-lib]
path = "../xi/core-lib"

[profile.release]
debug = 1
