[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl="=0.11.1"
url={path="../rust-url/url"}
[profile.release]
debug=1
[[bin]]
name="test_url57"
path="test_files/test_url57.rs"


[[bin]]
name="test_url26"
path="test_files/test_url26.rs"


[[bin]]
name="test_url54"
path="test_files/test_url54.rs"


[[bin]]
name="test_url47"
path="test_files/test_url47.rs"


[[bin]]
name="test_url6"
path="test_files/test_url6.rs"


[[bin]]
name="test_url36"
path="test_files/test_url36.rs"


[[bin]]
name="test_url39"
path="test_files/test_url39.rs"


[[bin]]
name="test_url4"
path="test_files/test_url4.rs"


[[bin]]
name="test_url34"
path="test_files/test_url34.rs"


[[bin]]
name="test_url58"
path="test_files/test_url58.rs"


[[bin]]
name="test_url28"
path="test_files/test_url28.rs"


[[bin]]
name="test_url14"
path="test_files/test_url14.rs"


[[bin]]
name="test_url33"
path="test_files/test_url33.rs"


[[bin]]
name="test_url16"
path="test_files/test_url16.rs"


[[bin]]
name="test_url55"
path="test_files/test_url55.rs"


[[bin]]
name="test_url12"
path="test_files/test_url12.rs"


[[bin]]
name="test_url20"
path="test_files/test_url20.rs"


[[bin]]
name="test_url9"
path="test_files/test_url9.rs"


[[bin]]
name="test_url2"
path="test_files/test_url2.rs"


[[bin]]
name="test_url29"
path="test_files/test_url29.rs"


[[bin]]
name="test_url27"
path="test_files/test_url27.rs"


[[bin]]
name="test_url5"
path="test_files/test_url5.rs"


[[bin]]
name="test_url40"
path="test_files/test_url40.rs"


[[bin]]
name="test_url50"
path="test_files/test_url50.rs"


[[bin]]
name="test_url23"
path="test_files/test_url23.rs"


[[bin]]
name="test_url25"
path="test_files/test_url25.rs"


[[bin]]
name="test_url42"
path="test_files/test_url42.rs"


[[bin]]
name="test_url3"
path="test_files/test_url3.rs"


[[bin]]
name="test_url0"
path="test_files/test_url0.rs"


[[bin]]
name="test_url46"
path="test_files/test_url46.rs"


[[bin]]
name="test_url56"
path="test_files/test_url56.rs"


[[bin]]
name="test_url10"
path="test_files/test_url10.rs"


[[bin]]
name="test_url38"
path="test_files/test_url38.rs"


[[bin]]
name="test_url17"
path="test_files/test_url17.rs"


[[bin]]
name="test_url49"
path="test_files/test_url49.rs"


[[bin]]
name="test_url41"
path="test_files/test_url41.rs"


[[bin]]
name="test_url53"
path="test_files/test_url53.rs"


[[bin]]
name="test_url60"
path="test_files/test_url60.rs"


[[bin]]
name="test_url31"
path="test_files/test_url31.rs"


[[bin]]
name="test_url52"
path="test_files/test_url52.rs"


[[bin]]
name="test_url24"
path="test_files/test_url24.rs"


[[bin]]
name="test_url43"
path="test_files/test_url43.rs"


[[bin]]
name="test_url21"
path="test_files/test_url21.rs"


[[bin]]
name="test_url37"
path="test_files/test_url37.rs"


[[bin]]
name="test_url22"
path="test_files/test_url22.rs"


[[bin]]
name="test_url1"
path="test_files/test_url1.rs"


[[bin]]
name="test_url32"
path="test_files/test_url32.rs"


[[bin]]
name="test_url18"
path="test_files/test_url18.rs"


[[bin]]
name="test_url48"
path="test_files/test_url48.rs"


[[bin]]
name="test_url8"
path="test_files/test_url8.rs"


[[bin]]
name="test_url61"
path="test_files/test_url61.rs"


[[bin]]
name="test_url51"
path="test_files/test_url51.rs"


[[bin]]
name="test_url7"
path="test_files/test_url7.rs"


[[bin]]
name="test_url15"
path="test_files/test_url15.rs"


[[bin]]
name="test_url11"
path="test_files/test_url11.rs"


[[bin]]
name="test_url59"
path="test_files/test_url59.rs"


[[bin]]
name="test_url13"
path="test_files/test_url13.rs"


[[bin]]
name="test_url44"
path="test_files/test_url44.rs"


[[bin]]
name="test_url19"
path="test_files/test_url19.rs"


[[bin]]
name="test_url35"
path="test_files/test_url35.rs"


[[bin]]
name="test_url45"
path="test_files/test_url45.rs"


[[bin]]
name="test_url30"
path="test_files/test_url30.rs"

