[package]
name = "toml_datetime"
version = "0.6.3"
keywords = [ "encoding", "toml",]
categories = [ "encoding", "parser-implementations", "parsing", "config",]
description = "A TOML-compatible datetime type"
authors = [ "Alex Crichton <alex@alexcrichton.com>",]

[dependencies]
bolero = "0.8.0"
arbitrary = "1.3.2"

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.include]
workspace = true

[dependencies.serde]
version = "1.0.145"
optional = true

[package.metadata.release]
[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "Unreleased"
replace = "{{version}}"
min = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...{{tag_name}}"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "ReleaseDate"
replace = "{{date}}"
min = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-header -->"
replace = "<!-- next-header -->\n## [Unreleased] - ReleaseDate\n"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-url -->"
replace = "<!-- next-url -->\n[Unreleased]: https://github.com/toml-rs/toml/compare/{{tag_name}}...HEAD"
exactly = 1

[package.metadata.docs.rs]
rustdoc-args = [ "--cfg", "docsrs",]
all-features = true
