[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl="=0.11.1"
semver={path="../semver"}
[profile.release]
debug=1
[[bin]]
name="test_semver1"
path="test_files/test_semver1.rs"


[[bin]]
name="test_semver0"
path="test_files/test_semver0.rs"


[[bin]]
name="test_semver2"
path="test_files/test_semver2.rs"


[[bin]]
name="test_semver3"
path="test_files/test_semver3.rs"


[[bin]]
name="test_semver4"
path="test_files/test_semver4.rs"
