[[bin]]
name="test_tui13"
path="replay_files/replay_tui13.rs"


[[bin]]
name="test_tui63"
path="replay_files/replay_tui63.rs"


[[bin]]
name="test_tui55"
path="replay_files/replay_tui55.rs"


[[bin]]
name="test_tui34"
path="replay_files/replay_tui34.rs"


[[bin]]
name="test_tui30"
path="replay_files/replay_tui30.rs"


[[bin]]
name="test_tui22"
path="replay_files/replay_tui22.rs"


[[bin]]
name="test_tui38"
path="replay_files/replay_tui38.rs"


[[bin]]
name="test_tui9"
path="replay_files/replay_tui9.rs"


[[bin]]
name="test_tui11"
path="replay_files/replay_tui11.rs"


[[bin]]
name="test_tui5"
path="replay_files/replay_tui5.rs"


[[bin]]
name="test_tui3"
path="replay_files/replay_tui3.rs"


[[bin]]
name="test_tui12"
path="replay_files/replay_tui12.rs"


[[bin]]
name="test_tui24"
path="replay_files/replay_tui24.rs"


[[bin]]
name="test_tui39"
path="replay_files/replay_tui39.rs"


[[bin]]
name="test_tui7"
path="replay_files/replay_tui7.rs"


[[bin]]
name="test_tui65"
path="replay_files/replay_tui65.rs"


[[bin]]
name="test_tui53"
path="replay_files/replay_tui53.rs"


[[bin]]
name="test_tui51"
path="replay_files/replay_tui51.rs"


[[bin]]
name="test_tui44"
path="replay_files/replay_tui44.rs"


[[bin]]
name="test_tui0"
path="replay_files/replay_tui0.rs"


[[bin]]
name="test_tui70"
path="replay_files/replay_tui70.rs"


[[bin]]
name="test_tui75"
path="replay_files/replay_tui75.rs"


[[bin]]
name="test_tui54"
path="replay_files/replay_tui54.rs"


[[bin]]
name="test_tui42"
path="replay_files/replay_tui42.rs"


[[bin]]
name="test_tui14"
path="replay_files/replay_tui14.rs"


[[bin]]
name="test_tui73"
path="replay_files/replay_tui73.rs"


[[bin]]
name="test_tui52"
path="replay_files/replay_tui52.rs"


[[bin]]
name="test_tui40"
path="replay_files/replay_tui40.rs"


[[bin]]
name="test_tui47"
path="replay_files/replay_tui47.rs"


[[bin]]
name="test_tui59"
path="replay_files/replay_tui59.rs"


[[bin]]
name="test_tui17"
path="replay_files/replay_tui17.rs"


[[bin]]
name="test_tui4"
path="replay_files/replay_tui4.rs"


[[bin]]
name="test_tui28"
path="replay_files/replay_tui28.rs"


[[bin]]
name="test_tui19"
path="replay_files/replay_tui19.rs"


[[bin]]
name="test_tui15"
path="replay_files/replay_tui15.rs"


[[bin]]
name="test_tui48"
path="replay_files/replay_tui48.rs"


[[bin]]
name="test_tui69"
path="replay_files/replay_tui69.rs"


[[bin]]
name="test_tui23"
path="replay_files/replay_tui23.rs"


[[bin]]
name="test_tui57"
path="replay_files/replay_tui57.rs"


[[bin]]
name="test_tui2"
path="replay_files/replay_tui2.rs"


[[bin]]
name="test_tui66"
path="replay_files/replay_tui66.rs"


[[bin]]
name="test_tui71"
path="replay_files/replay_tui71.rs"


[[bin]]
name="test_tui31"
path="replay_files/replay_tui31.rs"


[[bin]]
name="test_tui56"
path="replay_files/replay_tui56.rs"


[[bin]]
name="test_tui62"
path="replay_files/replay_tui62.rs"


[[bin]]
name="test_tui46"
path="replay_files/replay_tui46.rs"


[[bin]]
name="test_tui72"
path="replay_files/replay_tui72.rs"


[[bin]]
name="test_tui16"
path="replay_files/replay_tui16.rs"


[[bin]]
name="test_tui45"
path="replay_files/replay_tui45.rs"


[[bin]]
name="test_tui27"
path="replay_files/replay_tui27.rs"


[[bin]]
name="test_tui36"
path="replay_files/replay_tui36.rs"


[[bin]]
name="test_tui29"
path="replay_files/replay_tui29.rs"


[[bin]]
name="test_tui25"
path="replay_files/replay_tui25.rs"


[[bin]]
name="test_tui58"
path="replay_files/replay_tui58.rs"


[[bin]]
name="test_tui61"
path="replay_files/replay_tui61.rs"


[[bin]]
name="test_tui41"
path="replay_files/replay_tui41.rs"


[[bin]]
name="test_tui32"
path="replay_files/replay_tui32.rs"


[[bin]]
name="test_tui21"
path="replay_files/replay_tui21.rs"


[[bin]]
name="test_tui43"
path="replay_files/replay_tui43.rs"


[[bin]]
name="test_tui60"
path="replay_files/replay_tui60.rs"


[[bin]]
name="test_tui37"
path="replay_files/replay_tui37.rs"


[[bin]]
name="test_tui10"
path="replay_files/replay_tui10.rs"


[[bin]]
name="test_tui8"
path="replay_files/replay_tui8.rs"


[[bin]]
name="test_tui33"
path="replay_files/replay_tui33.rs"


[[bin]]
name="test_tui50"
path="replay_files/replay_tui50.rs"


[[bin]]
name="test_tui20"
path="replay_files/replay_tui20.rs"


[[bin]]
name="test_tui1"
path="replay_files/replay_tui1.rs"


[[bin]]
name="test_tui18"
path="replay_files/replay_tui18.rs"


[[bin]]
name="test_tui26"
path="replay_files/replay_tui26.rs"


[[bin]]
name="test_tui64"
path="replay_files/replay_tui64.rs"


[[bin]]
name="test_tui6"
path="replay_files/replay_tui6.rs"


[[bin]]
name="test_tui68"
path="replay_files/replay_tui68.rs"


[[bin]]
name="test_tui67"
path="replay_files/replay_tui67.rs"


[[bin]]
name="test_tui35"
path="replay_files/replay_tui35.rs"


[[bin]]
name="test_tui49"
path="replay_files/replay_tui49.rs"


[[bin]]
name="test_tui74"
path="replay_files/replay_tui74.rs"

[package]
name = "hello"
version = "0.1.0"
authors = [ "xiang",]
edition = "2018"

[dependencies.tui]
path = "../tui"

[profile.release]
debug = 1
