
[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug=1
[dependencies]

afl="=0.11.1"
http={path="../http"}

[[bin]]
name="test_http5"
path="test_files/test_http5.rs"


[[bin]]
name="test_http8"
path="test_files/test_http8.rs"


[[bin]]
name="test_http14"
path="test_files/test_http14.rs"


[[bin]]
name="test_http12"
path="test_files/test_http12.rs"


[[bin]]
name="test_http2"
path="test_files/test_http2.rs"


[[bin]]
name="test_http11"
path="test_files/test_http11.rs"


[[bin]]
name="test_http13"
path="test_files/test_http13.rs"


[[bin]]
name="test_http3"
path="test_files/test_http3.rs"


[[bin]]
name="test_http6"
path="test_files/test_http6.rs"


[[bin]]
name="test_http7"
path="test_files/test_http7.rs"


[[bin]]
name="test_http10"
path="test_files/test_http10.rs"


[[bin]]
name="test_http4"
path="test_files/test_http4.rs"


[[bin]]
name="test_http18"
path="test_files/test_http18.rs"


[[bin]]
name="test_http9"
path="test_files/test_http9.rs"


[[bin]]
name="test_http15"
path="test_files/test_http15.rs"


[[bin]]
name="test_http0"
path="test_files/test_http0.rs"


[[bin]]
name="test_http1"
path="test_files/test_http1.rs"


[[bin]]
name="test_http16"
path="test_files/test_http16.rs"


[[bin]]
name="test_http17"
path="test_files/test_http17.rs"

