[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl="=0.11.1"
tui={path="../tui"}
[profile.release]
debug=1
[[bin]]
name="test_tui19"
path="test_files/test_tui19.rs"


[[bin]]
name="test_tui67"
path="test_files/test_tui67.rs"


[[bin]]
name="test_tui36"
path="test_files/test_tui36.rs"


[[bin]]
name="test_tui39"
path="test_files/test_tui39.rs"


[[bin]]
name="test_tui15"
path="test_files/test_tui15.rs"


[[bin]]
name="test_tui11"
path="test_files/test_tui11.rs"


[[bin]]
name="test_tui42"
path="test_files/test_tui42.rs"


[[bin]]
name="test_tui38"
path="test_files/test_tui38.rs"


[[bin]]
name="test_tui59"
path="test_files/test_tui59.rs"


[[bin]]
name="test_tui66"
path="test_files/test_tui66.rs"


[[bin]]
name="test_tui57"
path="test_files/test_tui57.rs"


[[bin]]
name="test_tui58"
path="test_files/test_tui58.rs"


[[bin]]
name="test_tui8"
path="test_files/test_tui8.rs"


[[bin]]
name="test_tui7"
path="test_files/test_tui7.rs"


[[bin]]
name="test_tui4"
path="test_files/test_tui4.rs"


[[bin]]
name="test_tui60"
path="test_files/test_tui60.rs"


[[bin]]
name="test_tui69"
path="test_files/test_tui69.rs"


[[bin]]
name="test_tui5"
path="test_files/test_tui5.rs"


[[bin]]
name="test_tui43"
path="test_files/test_tui43.rs"


[[bin]]
name="test_tui25"
path="test_files/test_tui25.rs"


[[bin]]
name="test_tui56"
path="test_files/test_tui56.rs"


[[bin]]
name="test_tui23"
path="test_files/test_tui23.rs"


[[bin]]
name="test_tui9"
path="test_files/test_tui9.rs"


[[bin]]
name="test_tui70"
path="test_files/test_tui70.rs"


[[bin]]
name="test_tui73"
path="test_files/test_tui73.rs"


[[bin]]
name="test_tui72"
path="test_files/test_tui72.rs"


[[bin]]
name="test_tui45"
path="test_files/test_tui45.rs"


[[bin]]
name="test_tui55"
path="test_files/test_tui55.rs"


[[bin]]
name="test_tui37"
path="test_files/test_tui37.rs"


[[bin]]
name="test_tui40"
path="test_files/test_tui40.rs"


[[bin]]
name="test_tui31"
path="test_files/test_tui31.rs"


[[bin]]
name="test_tui62"
path="test_files/test_tui62.rs"


[[bin]]
name="test_tui26"
path="test_files/test_tui26.rs"


[[bin]]
name="test_tui74"
path="test_files/test_tui74.rs"


[[bin]]
name="test_tui52"
path="test_files/test_tui52.rs"


[[bin]]
name="test_tui22"
path="test_files/test_tui22.rs"


[[bin]]
name="test_tui35"
path="test_files/test_tui35.rs"


[[bin]]
name="test_tui28"
path="test_files/test_tui28.rs"


[[bin]]
name="test_tui20"
path="test_files/test_tui20.rs"


[[bin]]
name="test_tui12"
path="test_files/test_tui12.rs"


[[bin]]
name="test_tui54"
path="test_files/test_tui54.rs"


[[bin]]
name="test_tui1"
path="test_files/test_tui1.rs"


[[bin]]
name="test_tui50"
path="test_files/test_tui50.rs"


[[bin]]
name="test_tui41"
path="test_files/test_tui41.rs"


[[bin]]
name="test_tui53"
path="test_files/test_tui53.rs"


[[bin]]
name="test_tui68"
path="test_files/test_tui68.rs"


[[bin]]
name="test_tui10"
path="test_files/test_tui10.rs"


[[bin]]
name="test_tui64"
path="test_files/test_tui64.rs"


[[bin]]
name="test_tui3"
path="test_files/test_tui3.rs"


[[bin]]
name="test_tui0"
path="test_files/test_tui0.rs"


[[bin]]
name="test_tui2"
path="test_files/test_tui2.rs"


[[bin]]
name="test_tui18"
path="test_files/test_tui18.rs"


[[bin]]
name="test_tui61"
path="test_files/test_tui61.rs"


[[bin]]
name="test_tui30"
path="test_files/test_tui30.rs"


[[bin]]
name="test_tui24"
path="test_files/test_tui24.rs"


[[bin]]
name="test_tui46"
path="test_files/test_tui46.rs"


[[bin]]
name="test_tui33"
path="test_files/test_tui33.rs"


[[bin]]
name="test_tui6"
path="test_files/test_tui6.rs"


[[bin]]
name="test_tui63"
path="test_files/test_tui63.rs"


[[bin]]
name="test_tui29"
path="test_files/test_tui29.rs"


[[bin]]
name="test_tui47"
path="test_files/test_tui47.rs"


[[bin]]
name="test_tui14"
path="test_files/test_tui14.rs"


[[bin]]
name="test_tui49"
path="test_files/test_tui49.rs"


[[bin]]
name="test_tui71"
path="test_files/test_tui71.rs"


[[bin]]
name="test_tui48"
path="test_files/test_tui48.rs"


[[bin]]
name="test_tui17"
path="test_files/test_tui17.rs"


[[bin]]
name="test_tui44"
path="test_files/test_tui44.rs"


[[bin]]
name="test_tui27"
path="test_files/test_tui27.rs"


[[bin]]
name="test_tui13"
path="test_files/test_tui13.rs"


[[bin]]
name="test_tui65"
path="test_files/test_tui65.rs"


[[bin]]
name="test_tui75"
path="test_files/test_tui75.rs"


[[bin]]
name="test_tui21"
path="test_files/test_tui21.rs"


[[bin]]
name="test_tui32"
path="test_files/test_tui32.rs"


[[bin]]
name="test_tui51"
path="test_files/test_tui51.rs"


[[bin]]
name="test_tui34"
path="test_files/test_tui34.rs"


[[bin]]
name="test_tui16"
path="test_files/test_tui16.rs"
