[package]
name = "hello"
version = "0.1.0"
authors = ["xiang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl="=0.11.1"
time={path="../time"}
[profile.release]
debug=1
[[bin]]
name="test_time124"
path="test_files/test_time124.rs"


[[bin]]
name="test_time111"
path="test_files/test_time111.rs"


[[bin]]
name="test_time89"
path="test_files/test_time89.rs"


[[bin]]
name="test_time35"
path="test_files/test_time35.rs"


[[bin]]
name="test_time102"
path="test_files/test_time102.rs"


[[bin]]
name="test_time90"
path="test_files/test_time90.rs"


[[bin]]
name="test_time69"
path="test_files/test_time69.rs"


[[bin]]
name="test_time46"
path="test_files/test_time46.rs"


[[bin]]
name="test_time78"
path="test_files/test_time78.rs"


[[bin]]
name="test_time103"
path="test_files/test_time103.rs"


[[bin]]
name="test_time83"
path="test_files/test_time83.rs"


[[bin]]
name="test_time106"
path="test_files/test_time106.rs"


[[bin]]
name="test_time28"
path="test_files/test_time28.rs"


[[bin]]
name="test_time12"
path="test_files/test_time12.rs"


[[bin]]
name="test_time76"
path="test_files/test_time76.rs"


[[bin]]
name="test_time118"
path="test_files/test_time118.rs"


[[bin]]
name="test_time47"
path="test_files/test_time47.rs"


[[bin]]
name="test_time70"
path="test_files/test_time70.rs"


[[bin]]
name="test_time55"
path="test_files/test_time55.rs"


[[bin]]
name="test_time1"
path="test_files/test_time1.rs"


[[bin]]
name="test_time18"
path="test_files/test_time18.rs"


[[bin]]
name="test_time94"
path="test_files/test_time94.rs"


[[bin]]
name="test_time67"
path="test_files/test_time67.rs"


[[bin]]
name="test_time74"
path="test_files/test_time74.rs"


[[bin]]
name="test_time99"
path="test_files/test_time99.rs"


[[bin]]
name="test_time14"
path="test_files/test_time14.rs"


[[bin]]
name="test_time114"
path="test_files/test_time114.rs"


[[bin]]
name="test_time36"
path="test_files/test_time36.rs"


[[bin]]
name="test_time72"
path="test_files/test_time72.rs"


[[bin]]
name="test_time120"
path="test_files/test_time120.rs"


[[bin]]
name="test_time27"
path="test_files/test_time27.rs"


[[bin]]
name="test_time25"
path="test_files/test_time25.rs"


[[bin]]
name="test_time66"
path="test_files/test_time66.rs"


[[bin]]
name="test_time123"
path="test_files/test_time123.rs"


[[bin]]
name="test_time82"
path="test_files/test_time82.rs"


[[bin]]
name="test_time85"
path="test_files/test_time85.rs"


[[bin]]
name="test_time112"
path="test_files/test_time112.rs"


[[bin]]
name="test_time44"
path="test_files/test_time44.rs"


[[bin]]
name="test_time61"
path="test_files/test_time61.rs"


[[bin]]
name="test_time51"
path="test_files/test_time51.rs"


[[bin]]
name="test_time7"
path="test_files/test_time7.rs"


[[bin]]
name="test_time126"
path="test_files/test_time126.rs"


[[bin]]
name="test_time115"
path="test_files/test_time115.rs"


[[bin]]
name="test_time117"
path="test_files/test_time117.rs"


[[bin]]
name="test_time71"
path="test_files/test_time71.rs"


[[bin]]
name="test_time98"
path="test_files/test_time98.rs"


[[bin]]
name="test_time91"
path="test_files/test_time91.rs"


[[bin]]
name="test_time64"
path="test_files/test_time64.rs"


[[bin]]
name="test_time33"
path="test_files/test_time33.rs"


[[bin]]
name="test_time109"
path="test_files/test_time109.rs"


[[bin]]
name="test_time3"
path="test_files/test_time3.rs"


[[bin]]
name="test_time92"
path="test_files/test_time92.rs"


[[bin]]
name="test_time105"
path="test_files/test_time105.rs"


[[bin]]
name="test_time62"
path="test_files/test_time62.rs"


[[bin]]
name="test_time107"
path="test_files/test_time107.rs"


[[bin]]
name="test_time60"
path="test_files/test_time60.rs"


[[bin]]
name="test_time77"
path="test_files/test_time77.rs"


[[bin]]
name="test_time0"
path="test_files/test_time0.rs"


[[bin]]
name="test_time42"
path="test_files/test_time42.rs"


[[bin]]
name="test_time49"
path="test_files/test_time49.rs"


[[bin]]
name="test_time4"
path="test_files/test_time4.rs"


[[bin]]
name="test_time84"
path="test_files/test_time84.rs"


[[bin]]
name="test_time16"
path="test_files/test_time16.rs"


[[bin]]
name="test_time15"
path="test_files/test_time15.rs"


[[bin]]
name="test_time86"
path="test_files/test_time86.rs"


[[bin]]
name="test_time96"
path="test_files/test_time96.rs"


[[bin]]
name="test_time39"
path="test_files/test_time39.rs"


[[bin]]
name="test_time73"
path="test_files/test_time73.rs"


[[bin]]
name="test_time19"
path="test_files/test_time19.rs"


[[bin]]
name="test_time2"
path="test_files/test_time2.rs"


[[bin]]
name="test_time53"
path="test_files/test_time53.rs"


[[bin]]
name="test_time6"
path="test_files/test_time6.rs"


[[bin]]
name="test_time110"
path="test_files/test_time110.rs"


[[bin]]
name="test_time23"
path="test_files/test_time23.rs"


[[bin]]
name="test_time63"
path="test_files/test_time63.rs"


[[bin]]
name="test_time20"
path="test_files/test_time20.rs"


[[bin]]
name="test_time48"
path="test_files/test_time48.rs"


[[bin]]
name="test_time40"
path="test_files/test_time40.rs"


[[bin]]
name="test_time116"
path="test_files/test_time116.rs"


[[bin]]
name="test_time113"
path="test_files/test_time113.rs"


[[bin]]
name="test_time50"
path="test_files/test_time50.rs"


[[bin]]
name="test_time11"
path="test_files/test_time11.rs"


[[bin]]
name="test_time122"
path="test_files/test_time122.rs"


[[bin]]
name="test_time54"
path="test_files/test_time54.rs"


[[bin]]
name="test_time41"
path="test_files/test_time41.rs"


[[bin]]
name="test_time88"
path="test_files/test_time88.rs"


[[bin]]
name="test_time26"
path="test_files/test_time26.rs"


[[bin]]
name="test_time58"
path="test_files/test_time58.rs"


[[bin]]
name="test_time93"
path="test_files/test_time93.rs"


[[bin]]
name="test_time104"
path="test_files/test_time104.rs"


[[bin]]
name="test_time65"
path="test_files/test_time65.rs"


[[bin]]
name="test_time13"
path="test_files/test_time13.rs"


[[bin]]
name="test_time97"
path="test_files/test_time97.rs"


[[bin]]
name="test_time56"
path="test_files/test_time56.rs"


[[bin]]
name="test_time119"
path="test_files/test_time119.rs"


[[bin]]
name="test_time80"
path="test_files/test_time80.rs"


[[bin]]
name="test_time29"
path="test_files/test_time29.rs"


[[bin]]
name="test_time31"
path="test_files/test_time31.rs"


[[bin]]
name="test_time57"
path="test_files/test_time57.rs"


[[bin]]
name="test_time79"
path="test_files/test_time79.rs"


[[bin]]
name="test_time38"
path="test_files/test_time38.rs"


[[bin]]
name="test_time87"
path="test_files/test_time87.rs"


[[bin]]
name="test_time17"
path="test_files/test_time17.rs"


[[bin]]
name="test_time108"
path="test_files/test_time108.rs"


[[bin]]
name="test_time43"
path="test_files/test_time43.rs"


[[bin]]
name="test_time32"
path="test_files/test_time32.rs"


[[bin]]
name="test_time8"
path="test_files/test_time8.rs"


[[bin]]
name="test_time10"
path="test_files/test_time10.rs"


[[bin]]
name="test_time37"
path="test_files/test_time37.rs"


[[bin]]
name="test_time95"
path="test_files/test_time95.rs"


[[bin]]
name="test_time21"
path="test_files/test_time21.rs"


[[bin]]
name="test_time9"
path="test_files/test_time9.rs"


[[bin]]
name="test_time59"
path="test_files/test_time59.rs"


[[bin]]
name="test_time121"
path="test_files/test_time121.rs"


[[bin]]
name="test_time45"
path="test_files/test_time45.rs"


[[bin]]
name="test_time101"
path="test_files/test_time101.rs"


[[bin]]
name="test_time30"
path="test_files/test_time30.rs"


[[bin]]
name="test_time100"
path="test_files/test_time100.rs"


[[bin]]
name="test_time22"
path="test_files/test_time22.rs"


[[bin]]
name="test_time75"
path="test_files/test_time75.rs"


[[bin]]
name="test_time24"
path="test_files/test_time24.rs"


[[bin]]
name="test_time81"
path="test_files/test_time81.rs"


[[bin]]
name="test_time5"
path="test_files/test_time5.rs"


[[bin]]
name="test_time68"
path="test_files/test_time68.rs"


[[bin]]
name="test_time34"
path="test_files/test_time34.rs"


[[bin]]
name="test_time125"
path="test_files/test_time125.rs"


[[bin]]
name="test_time52"
path="test_files/test_time52.rs"

